const data = {
    products:[
        {
            _id: "1",
            name: "Nike Slim Shirt",
            category: "Shirts",
            image: "/images/product-1.jpg",
            price: 120,
            countInStock: 10,
            brand: "Nike",
            rating: 4.5,
            numReviews: 10,
            description: "High quality product",
        },
         {
            _id: "2",
            name: "Addidas Slim Shirt",
            category: "Shirts",
            image: "/images/product-2.jpg",
            price: 130,
            countInStock: 8,
            brand: "Addidas",
            rating: 3.5,
            numReviews: 34,
            description: "High quality product",
        },
         {
            _id: "3",
            name: "Puma Slim Shirt",
            category: "Shirts",
            image: "/images/product-3.jpg",
            price: 80,
            countInStock: 15,
            brand: "Puma",
            rating: 4.0,
            numReviews: 13,
            description: "High quality product",
        },
         {
            _id: "4",
            name: "Slazenger Slim Shirt",
            category: "Shirts",
            image: "/images/product-4.jpg",
            price: 60,
            countInStock: 11,
            brand: "Slazenger",
            rating: 4.5,
            numReviews: 10,
            description: "High quality product",
        },
         {
            _id: "5",
            name: "Umbro Slim Shirt",
            category: "Shirts",
            image: "/images/product-5.jpg",
            price: 90,
            countInStock: 0,
            brand: "Umbro",
            rating: 4.2,
            numReviews: 14,
            description: "High quality product",
        },
         {
            _id: "6",
            name: "Timberland Slim Shirt",
            category: "Shirts",
            image: "/images/product-6.jpg",
            price: 200,
            countInStock: 16,
            brand: "Timberland",
            rating: 4.5,
            numReviews: 28,
            description: "High quality product",
        },
    ],
};

export default data;